server:
  port:   10000

spring:
  application:
    name:   resourceservice
  data:
    mongodb:
      application-database:   resources
      username:   app_user
      password:   app_password
      database:   resources
      port:   27017
      host:   localhost